Update to look for mi-label JAR

diff --git a/src/main/resources/bin/generate b/src/main/resources/bin/generate
--- a/src/main/resources/bin/generate
+++ b/src/main/resources/bin/generate
@@ -53,15 +53,15 @@ PARENT_DIR=`cd ${SCRIPT_DIR}/.. && pwd`
 LIB_DIR=${PARENT_DIR}/lib
 
 # Check for dependencies.
-if [ ! -f ${LIB_DIR}/generate-*.jar ]; then
-    echo "Cannot find Generate Tool jar file in ${LIB_DIR}" 1>&2
+if [ ! -f ${LIB_DIR}/mi-label-*.jar ]; then
+    echo "Cannot find MILabel jar file in ${LIB_DIR}" 1>&2
     exit 1
 fi
 
 # Finds the jar file in LIB_DIR and sets it to GENERATE_JAR.
-GENERATE_JAR=`ls ${LIB_DIR}/generate-*.jar`
+GENERATE_JAR=`ls ${LIB_DIR}/mi-label-*.jar`
 
-# Executes PDS4 Generate Tool via the executable jar file
+# Executes MILabel software via the executable jar file
 # Arguments are passed in to the tool via '$@'
 ${JAVA_CMD} -jar ${GENERATE_JAR} "$@"
 
